### ISSUE TITLE
Wrong repository URL in description

### ISSUE THREAD

**Issue by slyshykO** [saeidjoker/libc.serial#1]
https://github.com/saeidjoker/libc.serial/blob/master/libc.serial/libc.serial.csproj#L9

**Comment by saeidjoker** [comment]
You are were welcome to fix this if you want. But I'll fix it in some minutes :-)

**Comment by sfmohassel** [comment]
This will be closed, because it is fixed in version 7.0.0. Thank you @slyshykO 👍
